name: build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'    
    
    - name: create dirs
      run: |
        mkdir class
        mkdir build
    
    - name: create .class
      run: javac -cp class/ src/com.schumakerteam.tetris.java -d bin n
      
    - name: create .jar
      run: |
        jar -cvfm build/MyGame.jar Manifest.txt -C bin/ . class/
   
    - name: upload .jar
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: /build
    
      
    
