name: build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'    
    
    - name: create dirs
      run: |
        mkdir class
        mkdir build
    
    - name: build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: create .jar
      run: |
        jar -cvfm build/MyGame.jar Manifest.txt -C build/ . class/
        
    - name: see dirs 
      run: |
        ls -al
        pwd
        cd class
        ls -al
        cd ..
        cd build
        ls -al
        cd ..
        pwd
   
    - name: upload .jar
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./build
    
      
    
